### ISSUE TITLE
update for Kodi 19?

### ISSUE THREAD

**Issue by Typhojd** [rmrector/service.stinger.notification#3]

**Comment by rmrector** [comment]
It is on my backlog, but low priority at the moment.

**Comment by rmrector** [comment]
Give [2.0.0](https://github.com/rmrector/repository.rector.stuff/tree/python3/service.stinger.notification) a try. I'll submit it to the official repo after some testing.

**Comment by Typhojd** [comment]
seems to work fine with rc1. Thank you
